FROM mcr.microsoft.com/devcontainers/javascript-node:1-20-bookworm

RUN apt update && \
    sudo apt install -y \
      libwebkit2gtk-4.0-dev \
      build-essential \
      curl \
      wget \
      file \
      libssl-dev \
      libgtk-3-dev \
      libayatana-appindicator3-dev \
      librsvg2-dev \
      libsoup2.4-dev \
      libjavascriptcoregtk-4.0-dev
