name: Privaxy Draft Build
on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 12 * * 1"

jobs:
  build:
    uses: ./.github/workflows/privaxy-build.yml
    with:
      upload-artifact: true
      upload-tag: "draft"
      build-linux: true
      build-windows: true
