name: Privaxy CI
on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - ".github/**"
      - ".devcontainer/**"
      - "*.md"
      - ".*"
  push:
    branches: [dev, v*]
    paths-ignore:
      - ".github/**"
      - ".devcontainer/**"
      - "*.md"
      - ".*"

jobs:
  build:
    uses: ./.github/workflows/privaxy-build.yml
    with:
      upload-artifact: false
      build-linux: true
      build-windows: false

  check:
    needs:
      - build
    if: ${{ always() }}
    uses: ./.github/workflows/check.yml


